# Change these first
owner: Zollege # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ZQL
    url: https://zql.zollege.com/api/ping/
  - name: Reports (Metabase)
    url: https://reports.zollege.com/api/health
  - name: Learn (Canvas)
    url: https://learn.zollege.com/health_check/
  - name: Zollege
    url: https://zollege.com/
  - name: Abilene Dental Assistant School
    url: https://abilenedentalassistantschool.com/
  - name: Abilene Medical Assistant School
    url: https://abilenemedicalassistant.com/
  - name: Alvin Dental Assistant School
    url: https://alvindentalassistant.com/
  - name: Amarillo Dental Assistant School
    url: https://amarillodentalassistantschool.com/
  - name: Amarillo Medical Assistant School
    url: https://amarillomedicalassistantschool.com/
  - name: Arch Dental Academy
    url: https://archdentalacademy.com/
  - name: Atlanta Dental Assistant School
    url: https://atlantadentalassistantschool.com/
  - name: Atlanta Medical Assistant School
    url: https://atlantamedicalassistant.com/
  - name: Augusta Dental Assistant School
    url: https://augustadentalassistant.com/
  - name: Austin Coding Academy
    url: https://austincodingacademy.com/
  - name: Austin Dental Assistant School
    url: https://austindentalassistantschool.com/
  - name: Austin Medical Assistant School
    url: https://austinmedicalassistantschool.com/
  - name: Baton Rouge Dental Assistant Academy
    url: https://batonrougedentalassistant.com/
  - name: Bellingham Dental Assistant School
    url: https://bellinghamdentalassistant.com/
  - name: Birmingham Dental Assistant School
    url: https://birminghamdentalassistant.com/
  - name: Bloomington Dental Assistant School
    url: https://bloomingtondentalassistant.com/
  - name: Bremerton Dental Assistant School
    url: https://bremertondentalassistant.com/
  - name: Brownsville Dental Assistant School 
    url: https://brownsvilledentalassistant.com/
  - name: Centralia Dental Assistant School
    url: https://centraliadentalassistant.com/
  - name: Charlotte Dental Assistant School
    url: https://charlottedentalassistantschool.com/
  - name: Chicago Dental Assistant School
    url: https://chicagodentalassistantschool.com/
  - name: College Station Dental Assistant School
    url: https://collegestationdentalassistant.com/
  - name: College Station Medical Assistant School
    url: https://collegestationmedicalassistant.com/
  - name: Colorado Dental Assistant Academy
    url: https://coloradodentalassistant.com/
  - name: Corpus Christi Dental Assistant School
    url: https://corpuschristidentalassistant.com/
  - name: Corpus Christi Medical Assistant School
    url: https://corpuschristimedicalassistant.com/
  - name: Dallas Dental Assistant School
    url: https://dallasdentalassistantschool.com/
  - name: Dallas Medical Assistant School
    url: https://dallasmedicalassistant.com/
  - name: Dalton Dental Assistant School
    url: https://daltondentalassistant.com/
  - name: Denton Dental Assistant School
    url: http://dentondentalassistant.com/
  - name: Denver Dental Assistant School
    url: https://denverdentalassistant.com/
  - name: Duncanville Dental Assistant School
    url: https://duncanvilledentalassistant.com/
  - name: El Paso Dental Assistant School
    url: https://elpasodentalassistant.com/
  - name: El Paso Medical Assistant School
    url: https://elpasomedicalassistant.com/
  - name: Evansville Dental Assistant School
    url: https://evansvilledentalassistantschool.com/
  - name: Fort Worth Dental Assistant School
    url: https://fortworthdentalassistant.com/
  - name: Franklin Dental Assistant School
    url: https://franklindentalassistant.com/
  - name: Georgia Dental Assistant School
    url: https://georgiadentalassistantschool.com/
  - name: Gonzales Medical Assistant School
    url: https://gonzalesmedicalassistant.com/
  - name: Granbury Medical Assistant School
    url: https://granburymedicalassistant.com/
  - name: Grapevine Dental Assistant School
    url: https://grapevinedentalassistantschool.com/
  - name: Houma Dental Assistant School
    url: https://houmadentalassistant.com/
  - name: Houston Dental Assistant Academy
    url: https://houstondentalassistant.com/
  - name: Huntsville Dental Assistant School
    url: https://huntsvilledentalassistant.com/
  - name: Huntsville Dental Assistant School
    url: https://huntsvilledentalassistantschool.com/
  - name: Indianapolis Dental Assistant School
    url: https://indydentalassistantschool.com/
  - name: Jacksonville Dental Assistant School
    url: https://jacksonvilledentalassistantschool.com/
  - name: Jeffersonville Dental Assistant School
    url: https://jeffersonvilledentalassistant.com/
  - name: Lafayette Dental Assistant School
    url: https://lafayettedentalassistant.com/
  - name: Lake Jackson Medical Assistant School
    url: https://lakejacksonmedicalassistant.com/
  - name: Las Vegas Dental Assistant School
    url: https://lasvegasdentalassistant.com/
  - name: Las Vegas Medical Assistant School
    url: https://lasvegasmedicalassistant.com/
  - name: League City Medical Assistant School
    url: https://leaguecitymedicalassistant.com/
  - name: Little Rock Dental Assistant Academy
    url: https://littlerockdentalassistant.com/
  - name: Louisiana Dental Assistant Academy
    url: https://louisianadentalassistantacademy.com/
  - name: Lubbock Coding Academy
    url: https://lubbockcodingacademy.com/
  - name: Lubbock Dental Assistant School
    url: https://lubbockdentalassistantschool.com/
  - name: Lubbock Medical Assistant School
    url: https://lubbockmedicalassistant.com/
  - name: Magnolia Dental Assistant School
    url: https://magnoliadentalassistant.com/
  - name: McKinney Dental Assistant School
    url: https://mckinneydentalassistant.com/
  - name: Midland Dental Assistant School
    url: https://midlanddentalassistant.com/
  - name: Montgomery Dental Assistant School
    url: https://montgomerydentalassistant.com/
  - name: Moses Lake Dental Assistant School
    url: https://moseslakedentalassistant.com/
  - name: Nacogdoches Dental Assistant School
    url: https://nacogdochesdentalassistant.com/
  - name: New Braunfels Dental Assistant School
    url: https://newbraunfelsdentalassistant.com/
  - name: New Orleans Dental Assistant School
    url: https://neworleansdentalassistant.com/
  - name: Odessa Dental Assistant School
    url: https://odessadentalassistantschool.com/
  - name: Ohio Dental Assistant School
    url: https://ohiodentalassistantschool.com/
  - name: Oklahoma City Dental Assistant School
    url: https://oklahomacitydentalassistant.com/
  - name: Olympia Dental Assistant School
    url: https://olympiadentalassistant.com/
  - name: Philadelphia Medical Assistant School
    url: https://philadelphiamedicalassistantschool.com/
  - name: Phoenix Dental Assistant School
    url: https://phoenixdentalassistantschool.com/
  - name: San Antonio Dental Assistant School
    url: https://sanantoniodentalassistantschool.com/
  - name: San Antonio Medical Assistant School
    url: https://sanantoniomedicalassistant.com/
  - name: San Francisco Medical Assistant School
    url: https://sanfranciscomedicalassistantschool.com/
  - name: San Marcos Dental Assistant School
    url: https://sanmarcosdentalassistant.com/
  - name: Savannah Dental Assistant School
    url: https://savannahdentalassistant.com/
  - name: Searcy Dental Assistant School
    url: https://searcydentalassistant.com/
  - name: Seattle Dental Assistant School
    url: https://seattledentalassistant.com/
  - name: Shreveport Dental Assistant School
    url: https://shreveportdentalassistant.com/
  - name: Snap Medical Assistant Academy
    url: https://snapmedicalassistant.com/
  - name: South Bend Dental Assistant School
    url: https://southbenddentalassistant.com/
  - name: Spokane Dental Assistant School
    url: https://spokanedentalassistant.com/
  - name: St. John Dental Assistant School
    url: https://stjohndentalassistant.com/
  - name: Tacoma Dental Assistant School
    url: https://tacomadentalassistant.com/
  - name: Temple Dental Assistant School
    url: https://templedentalassistantschool.com/
  - name: Terre Haute Dental Assistant School
    url: https://terrehautedentalassistant.com/
  - name: Texas Dental Assistant School
    url: https://texasdentalassistantschool.com/
  - name: Texas Tech Coding Academy
    url: https://texastechcodingacademy.com/
  - name: Tucson Dental Assistant School
    url: https://tucsondentalassistantschool.com/
  - name: Tulsa Dental Assistant School
    url: https://tulsadentalassistant.com/
  - name: Tulsa Medical Assistant School
    url: https://tulsamedicalassistant.com/
  - name: Tyler Dental Assistant School
    url: https://tylerdentalassistant.com/
  - name: Waco Dental Assistant School
    url: https://dentalassistantschoolwaco.com/
  - name: Wichita Falls Dental Assistant School
    url: https://wichitafallsdentalassistant.com/
  - name: Wichita Falls Medical Assistant School
    url: https://wichitafallsmedicalassistant.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zollege.com
  # baseUrl: /your-repo-name
  logoUrl: https://zollege.com/wp-content/uploads/2020/06/Zollege_Logo_Blue_1.png
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Technology
      href: https://technology.zollege.com/
    - title: Hubspot
      href: https://status.hubspot.com/
    - title: Slack
      href: https://status.slack.com/
    - title: GitHub
      href: https://www.githubstatus.com/
    - title: Heroku
      href: https://status.heroku.com/
    - title: Cloudflare
      href: https://www.cloudflarestatus.com/
    - title: AWS
      href: https://status.aws.amazon.com/
      
  customHeadHtml: "<style>.container:nth-of-type(1) { max-width: 100% }</style>"
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
