
   
# Change these first
owner: Zollege # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ZQL
    url: https://zql.zollege.com/api/ping/
  - name: Reports (Metabase)
    url: https://reports.zollege.com/api/health
  - name: Learn (Canvas)
    url: https://learn.zollege.com/health_check/
  - name: Zollege
    url: https://zollege.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zollege.com
  # baseUrl: /your-repo-name
  logoUrl: https://zollege.com/wp-content/uploads/2020/06/Zollege_Logo_Blue_1.png
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: Technology
      href: https://technology.zollege.com/
    - title: Hubspot
      href: https://status.hubspot.com/
    - title: Slack
      href: https://status.slack.com/
    - title: Heroku
      href: https://status.heroku.com/
    - title: Cloudflare
      href: https://www.cloudflarestatus.com/
    - title: AWS
      href: https://status.aws.amazon.com/
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
